source 'https://github.com/CocoaPods/Specs'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'UnityFramework' do
  pod 'Google-Mobile-Ads-SDK', '~> 10.5'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
